export const projects = [
  {
    id: "year-1-backend-rest-api",
    title: "שרת לניהול תיכון החממה",
    description: "בתיכון החממה יש הרבה דברים שאנחנו עושים ידנית או עם גוגל- אבל אתה יכול לוודא שלא",
    longDescription: "חפשו בעיה בתוך התיכון (לדוגמה- קבוצות למידה) ותנסו להכין שרת פשוט בשביל לנהל אותו",
    difficulty: "קל" as const,
    estimatedTime: "6-7 שעות",
    skills: ["python", "flask"],
    featured: true,
  },
  {
    id: "year-1-backend-application",
    title: "אפליציה לתיכון החממה",
    description: "רוצים לחדש קצת את התיכון? תכינו אפליקציה לניהול משהו בתיכון",
    longDescription: "חפשו בעיה בתוך התיכון (לדוגמה- קבוצות למידה) ותנסו להכין אפליקציה פשוטה בשביל לנהל אותו",
    difficulty: "קל" as const,
    estimatedTime: "7-8 שעות",
    skills: ["python", "QT / PyQt6"],
    featured: false,
  },
  {
    id: "year-1-backend-auth",
    title: "מערכת אימות בסיסית",
    description: "הטמע פונקציונליות רישום והתחברות משתמשים",
    longDescription: "",
    difficulty: "Intermediate" as const,
    estimatedTime: "6-8 שעות",
    skills: ["Node.js", "Express", "אימות", "אבטחה"],
    featured: true,
  },
];
