export const projects = [
  {
    id: "year-1-datascience-pandas",
    title: "Analyzing data with python",
    description: "Analyze data from the real world using the python lanaguage and it's pandas library",
    longDescription: "",
    difficulty: "Beginner" as const,
    estimatedTime: "4-5 hours",
    skills: ["Python", "Pandas", "Data analysis"],
    featured: true,
  },
  {
    id: "year-1-datascience-visualization",
    title: "לDashboard and Metrics for Data Visualization",
    description: "Create visualizations using Matplotlib & Seaborn",
    longDescription: "",
    difficulty: "Intermediate" as const,
    estimatedTime: "5-6 hours",
    skills: ["Python", "Matplotlib", "Seaborn", "Visuilization"],
    featured: true,
  },
  {
    id: "year-1-datascience-cleaning",
    title: "Data cleaning project",
    description: "Clean and prepare unnecessary and broken data",
    longDescription: "",
    difficulty: "Intermediate" as const,
    estimatedTime: "4-5 hours",
    skills: ["Python", "Pandas", "Data cleaning", "NumPy"],
    featured: true,
  },
];