export const projects = [
  {
    id: "year-1-devops-ci-pipeline",
    title: "צינור CI בסיסי",
    description: "הגדר צינור CI פשוט עם GitHub Actions",
    longDescription: "",
    difficulty: "בינוני" as const,
    estimatedTime: "5-6 שעות",
    skills: ["GitHub Actions", "CI/CD", "אוטומציה"],
    featured: true,
  },
  {
    id: "year-1-devops-http-server",
    title: "Build Your Own HTTP Server",
    description: "Implement a basic HTTP server from scratch using Python sockets",
    longDescription: "Learn how HTTP works under the hood by building your own web server. You'll implement socket programming, handle HTTP requests and responses, parse headers, serve static files, and understand the fundamentals of client-server communication. This project will give you deep insights into how web servers like Apache and Nginx work at a low level.",
    difficulty: "בינוני" as const,
    estimatedTime: "6-8 hours",
    skills: ["Python", "Sockets", "HTTP Protocol", "Networking", "TCP/IP"],
    featured: true,
  },
  {
    id: "year-1-devops-mock-network",
    title: "Mock Network Implementation",
    description: "Create a simulated network environment to understand packet routing and protocols",
    longDescription: "Build a network simulator that demonstrates how packets travel through a network. Implement routers, switches, and hosts in software. Simulate packet routing, address resolution, and basic network protocols. This hands-on project will solidify your understanding of network architecture, the OSI model, and how data flows across networks.",
    difficulty: "בינוני" as const,
    estimatedTime: "8-10 hours",
    skills: ["Python", "Network Protocols", "Routing", "OSI Model", "Packet Simulation"],
    featured: true,
  },
];
