export const projects = [
  {
    id: "year-1-frontend-portfolio",
    title: "אתר תיק עבודות אישי",
    description: "בנה תיק עבודות אישי רספונסיבי באמצעות HTML, CSS ו-JavaScript בסיסי",
    longDescription: "",
    difficulty: "Beginner" as const,
    estimatedTime: "3-4 שעות",
    skills: ["HTML5", "CSS3", "עיצוב רספונסיבי"],
    featured: true,
  },
  {
    id: "year-1-frontend-landing",
    title: "אתר בית אישי יצירתי",
    description: "צרו אתר בית ייחודי עם 2 עמודים - לבית הספר, למשפחה, לתחביב או לספר את הסיפור שלכם",
    longDescription: "בחרו נושא שמעניין אתכם ובנו אתר בית מקורי עם 2 עמודים בלבד! זה יכול להיות:\n• אתר למועדון הספרים של המשפחה (עמוד ראשי + רשימת ספרים)\n• דף לתיעוד הרפתקאות הטיולים שלכם (עמוד בית + גלריה)\n• אתר לחנות הממתקים החלומית שלכם (עמוד ראשי + תפריט)\n• פורטל לסיפורי הילדות שלכם (עמוד בית + סיפור)\n• אתר לפרויקט הקהילתי שלכם (עמוד ראשי + פרטים)\n• דף הביתה של חברת הזיכרונות המשפחתית (עמוד בית + שירותים)\n\nהמטרה היא ללמוד HTML/CSS דרך יצירת משהו אישי ומשמעותי בקנה מידה קטן ומנוהל!",
    difficulty: "Beginner" as const,
    estimatedTime: "2-3 שעות",
    skills: ["HTML", "CSS", "Flexbox", "Grid", "יצירתיות"],
    featured: false,
    videoUrl: "https://www.youtube.com/watch?v=G3e-cpL7ofc",
    demoUrl: "https://example-portfolio.netlify.app",
    tutorialUrl: "https://developer.mozilla.org/en-US/docs/Learn/HTML"
  },
  {
    id: "year-1-frontend-calculator",
    title: "מחשבון אינטראקטיבי",
    description: "בנה מחשבון פונקציונלי עם JavaScript",
    longDescription: "",
    difficulty: "Intermediate" as const,
    estimatedTime: "4-5 שעות",
    skills: ["HTML", "CSS", "JavaScript", "מניפולציה של DOM"],
    featured: true,
  },
];
