export const projects = [
  {
    id: "year-2-backend-microservices",
    title: "ארכיטקטורת מיקרו-שירותים",
    description: "בנה מערכת מיקרו-שירותים עם API Gateway ו-Service Discovery",
    longDescription: "פיתוח מערכת מיקרו-שירותים מלאה הכוללת מספר שירותים עצמאיים, API Gateway, service discovery, load balancing ותקשורת בין השירותים.",
    difficulty: "Advanced" as const,
    estimatedTime: "25-30 שעות",
    skills: ["Node.js/Spring Boot", "Docker", "API Gateway", "Service Discovery", "Message Queues"],
    featured: true,
  },
  {
    id: "year-2-backend-graphql",
    title: "GraphQL API מתקדם",
    description: "פתח API GraphQL עם subscriptions ו-real-time updates",
    longDescription: "בניית GraphQL server מתקדם עם תמיכה ב-subscriptions, DataLoader לאופטימיזציה, caching מתקדם ואבטחה.",
    difficulty: "Advanced" as const,
    estimatedTime: "15-20 שעות",
    skills: ["GraphQL", "Apollo Server", "DataLoader", "Subscriptions", "Schema Design"],
    featured: false,
  },
  {
    id: "year-2-backend-streaming",
    title: "מערכת עיבוד זרמי נתונים",
    description: "בנה מערכת לעיבוד real-time data streams",
    longDescription: "פיתוח מערכת לעיבוד זרמי נתונים בזמן אמת עם Apache Kafka/Redis Streams, עיבוד אסינכרוני ואחסון מתקדם.",
    difficulty: "Expert" as const,
    estimatedTime: "30-35 שעות",
    skills: ["Kafka/Redis Streams", "Stream Processing", "Event Sourcing", "CQRS", "Analytics"],
    featured: true,
  },
  {
    id: "year-2-backend-auth-system",
    title: "מערכת אימות מתקדמת",
    description: "פתח מערכת authentication ו-authorization מלאה",
    longDescription: "בניית מערכת אימות מקיפה עם JWT, OAuth2, 2FA, role-based access control ואבטחה מתקדמת.",
    difficulty: "Intermediate" as const,
    estimatedTime: "12-18 שעות",
    skills: ["JWT", "OAuth2", "2FA", "RBAC", "Security", "Session Management"],
    featured: false,
  },
];