export const projects = [
  {
    id: "year-2-devops-kubernetes-cluster",
    title: "Kubernetes Cluster בפרודקשן",
    description: "הקם ונהל Kubernetes cluster מלא עם ניטור ולוגים",
    longDescription: "הקמת production-ready Kubernetes cluster עם Ingress Controller, cert-manager, monitoring stack (Prometheus + Grafana), logging (ELK), ו-CI/CD pipeline.",
    difficulty: "Advanced" as const,
    estimatedTime: "25-35 שעות",
    skills: ["Kubernetes", "Helm", "Prometheus", "Grafana", "ELK Stack", "CI/CD"],
    featured: true,
  },
  {
    id: "year-2-devops-terraform-infrastructure",
    title: "Infrastructure as Code עם Terraform",
    description: "בנה תשתית ענן מלאה עם Terraform",
    longDescription: "פיתוח מודולי Terraform לבניית תשתית ענן מורכבת כולל networking, security groups, load balancers, databases ו-monitoring.",
    difficulty: "Intermediate" as const,
    estimatedTime: "20-25 שעות",
    skills: ["Terraform", "AWS/Azure", "Infrastructure as Code", "Networking", "Security"],
    featured: false,
  },
  {
    id: "year-2-devops-cicd-pipeline",
    title: "CI/CD Pipeline מתקדם",
    description: "צור pipeline אוטומטי מלא עם בדיקות ופריסה",
    longDescription: "בניית CI/CD pipeline מקיף עם automated testing, security scanning, containerization, deployment strategies ו-rollback capabilities.",
    difficulty: "Advanced" as const,
    estimatedTime: "18-22 שעות",
    skills: ["Jenkins/GitHub Actions", "Docker", "Testing", "Security Scanning", "Deployment Strategies"],
    featured: true,
  },
  {
    id: "year-2-devops-monitoring-stack",
    title: "מערכת ניטור מקיפה",
    description: "הקם מערכת ניטור ו-alerting מתקדמת",
    longDescription: "בניית מערכת ניטור מלאה עם metrics collection, log aggregation, alerting rules, dashboards ו-incident response automation.",
    difficulty: "Advanced" as const,
    estimatedTime: "15-20 שעות",
    skills: ["Prometheus", "Grafana", "ELK/EFK", "AlertManager", "PagerDuty", "Automation"],
    featured: false,
  },
];