export const projects = [
  {
    id: "year-2-frontend-ecommerce",
    title: "אפליקציית E-commerce מלאה",
    description: "בנה חנות אונליין מלאה עם React, TypeScript ו-Redux",
    longDescription: "פיתוח אפליקציית e-commerce מורכבת הכוללת ניהול מוצרים, עגלת קניות, תשלומים ואזור ניהול. שימוש ב-React עם TypeScript, Redux לניהול state, ואינטגרציה עם API backend.",
    difficulty: "Intermediate" as const,
    estimatedTime: "15-20 שעות",
    skills: ["React", "TypeScript", "Redux Toolkit", "React Router", "API Integration", "Testing"],
    featured: true,
  },
  {
    id: "year-2-frontend-dashboard",
    title: "דשבורד אנליטיקה",
    description: "צור דשבורד אינטראקטיבי עם גרפים וויזואליזציות נתונים",
    longDescription: "בניית דשבורד מתקדם להצגת נתונים עם גרפים אינטראקטיביים, פילטרים דינמיים ותצוגות responsive. שימוש בספריות ויזואליזציה מתקדמות.",
    difficulty: "Advanced" as const,
    estimatedTime: "12-15 שעות",
    skills: ["React", "D3.js", "Chart.js", "Data Visualization", "Real-time Updates"],
    featured: false,
  },
  {
    id: "year-2-frontend-pwa",
    title: "Progressive Web App (PWA)",
    description: "פתח אפליקציית web מתקדמת שעובדת offline",
    longDescription: "יצירת PWA מלאה עם יכולות offline, push notifications, service workers ואפשרות התקנה על מכשירים ניידים.",
    difficulty: "Advanced" as const,
    estimatedTime: "18-25 שעות",
    skills: ["PWA", "Service Workers", "IndexedDB", "Push Notifications", "Web APIs"],
    featured: true,
  },
  {
    id: "year-2-frontend-realtime",
    title: "אפליקציית צ'אט בזמן אמת",
    description: "בנה אפליקציית צ'אט עם WebSocket ותכונות מתקדמות",
    longDescription: "פיתוח אפליקציית צ'אט מתקדמת עם תמיכה בחדרים, הודעות פרטיות, שיתוף קבצים ותכונות collaboration בזמן אמת.",
    difficulty: "Advanced" as const,
    estimatedTime: "20-25 שעות",
    skills: ["WebSocket", "Real-time Communication", "File Upload", "User Authentication", "Chat UI"],
    featured: false,
  },
];