export const projects = [
  {
    id: "year-3-backend-event-driven",
    title: "Event-Driven Architecture עם CQRS",
    description: "בנה מערכת מורכבת עם Event Sourcing ו-CQRS",
    longDescription: "פיתוח מערכת מתקדמת המבוססת על Event Sourcing, CQRS, event store, projections, ו-saga orchestration לניהול עסקאות מורכבות.",
    difficulty: "Expert" as const,
    estimatedTime: "45-55 שעות",
    skills: ["Event Sourcing", "CQRS", "Event Store", "Saga Pattern", "Domain-Driven Design"],
    featured: true,
  },
  {
    id: "year-3-backend-distributed-system",
    title: "מערכת מבוזרת בקנה מידה גדול",
    description: "בנה מערכת מבוזרת עם consensus ו-fault tolerance",
    longDescription: "פיתוח מערכת מבוזרת מורכבת עם Raft consensus, distributed caching, circuit breakers, ו-advanced monitoring לטיפול בכשלים.",
    difficulty: "Expert" as const,
    estimatedTime: "50-60 שעות",
    skills: ["Distributed Systems", "Raft Consensus", "Fault Tolerance", "Circuit Breakers", "Distributed Caching"],
    featured: true,
  },
  {
    id: "year-3-backend-high-performance",
    title: "High-Performance API Gateway",
    description: "פתח API Gateway מותאם לביצועים גבוהים",
    longDescription: "בניית API Gateway מתקדם עם rate limiting, load balancing algorithms, caching strategies, ו-performance optimization למיליוני requests ליום.",
    difficulty: "Expert" as const,
    estimatedTime: "35-40 שעות",
    skills: ["API Gateway", "High Performance", "Rate Limiting", "Load Balancing", "Performance Tuning"],
    featured: false,
  },
  {
    id: "year-3-backend-blockchain",
    title: "Blockchain-based System",
    description: "בנה מערכת המבוססת על blockchain וחוזים חכמים",
    longDescription: "פיתוח מערכת המשתמשת בטכנולוגיית blockchain, smart contracts, ו-decentralized storage לפתרון בעיות אמון ושקיפות.",
    difficulty: "Expert" as const,
    estimatedTime: "40-50 שעות",
    skills: ["Blockchain", "Smart Contracts", "Ethereum/Solidity", "Web3", "Decentralized Systems"],
    featured: false,
  },
];