export const projects = [
  {
    id: "year-3-datascience-research-project",
    title: "פרויקט מחקר AI מקורי",
    description: "בצע מחקר מקורי ופרסם paper בתחום AI",
    longDescription: "ביצוע מחקר מקורי בתחום AI כולל סקר ספרות, הגדרת בעיה, עיצוב ניסויים, יישום algorithms חדשניים, ופרסום תוצאות.",
    difficulty: "Expert" as const,
    estimatedTime: "80-120 שעות",
    skills: ["Research Methodology", "Paper Writing", "Original Algorithms", "Statistical Analysis", "Peer Review"],
    featured: true,
  },
  {
    id: "year-3-datascience-multimodal-ai",
    title: "מודל AI רב-מודלי",
    description: "פתח מודל המשלב טקסט, תמונה ואודיו",
    longDescription: "בניית מודל מתקדם המשלב multiple modalities (טקסט, תמונה, אודיו) עם transformer architectures, attention mechanisms, ו-cross-modal learning.",
    difficulty: "Expert" as const,
    estimatedTime: "60-80 שעות",
    skills: ["Multimodal AI", "Transformers", "Cross-Modal Learning", "Vision-Language Models", "Advanced Architectures"],
    featured: true,
  },
  {
    id: "year-3-datascience-federated-learning",
    title: "Federated Learning System",
    description: "בנה מערכת federated learning לפרטיות נתונים",
    longDescription: "פיתוח מערכת federated learning מקיפה הכוללת aggregation algorithms, differential privacy, ו-secure multiparty computation.",
    difficulty: "Expert" as const,
    estimatedTime: "45-55 שעות",
    skills: ["Federated Learning", "Differential Privacy", "Secure Computation", "Distributed ML", "Privacy-Preserving AI"],
    featured: false,
  },
  {
    id: "year-3-datascience-automl-platform",
    title: "AutoML Platform",
    description: "צור פלטפורמה לבניית מודלים אוטומטית",
    longDescription: "בניית פלטפורמה מתקדמת ל-AutoML הכוללת automated feature engineering, hyperparameter optimization, neural architecture search, ו-model interpretation.",
    difficulty: "Expert" as const,
    estimatedTime: "70-90 שעות",
    skills: ["AutoML", "Neural Architecture Search", "Hyperparameter Optimization", "Feature Engineering", "Model Interpretation"],
    featured: false,
  },
];