export const projects = [
  {
    id: "year-3-devops-multi-cloud",
    title: "Multi-Cloud Platform",
    description: "בנה פלטפורמה הרצה על מספר ספקי ענן",
    longDescription: "פיתוח פלטפורמה מתקדמת הרצה על AWS, Azure ו-GCP בו-זמנית, עם disaster recovery, cost optimization, ו-unified management interface.",
    difficulty: "Expert" as const,
    estimatedTime: "50-65 שעות",
    skills: ["Multi-Cloud", "AWS", "Azure", "GCP", "Disaster Recovery", "Cost Optimization"],
    featured: true,
  },
  {
    id: "year-3-devops-platform-engineering",
    title: "Internal Developer Platform",
    description: "צור פלטפורמת פיתוח פנימית מלאה",
    longDescription: "בניית פלטפורמה מקיפה לצוותי פיתוח הכוללת self-service deployment, monitoring, logging, security scanning, ו-developer portal.",
    difficulty: "Expert" as const,
    estimatedTime: "60-75 שעות",
    skills: ["Platform Engineering", "Self-Service", "Developer Experience", "Portal Development", "Automation"],
    featured: true,
  },
  {
    id: "year-3-devops-chaos-engineering",
    title: "Chaos Engineering Framework",
    description: "פתח framework לבדיקת עמידות מערכות",
    longDescription: "בניית framework מתקדם ל-chaos engineering הכולל automated failure injection, monitoring, ו-resilience testing למערכות מבוזרות.",
    difficulty: "Expert" as const,
    estimatedTime: "35-45 שעות",
    skills: ["Chaos Engineering", "Resilience Testing", "Failure Injection", "Observability", "Automation"],
    featured: false,
  },
  {
    id: "year-3-devops-gitops-advanced",
    title: "GitOps Pipeline מתקדם",
    description: "בנה GitOps workflow עם progressive delivery",
    longDescription: "פיתוח GitOps pipeline מתקדם עם canary deployments, feature flags, automated rollbacks, ו-multi-environment promotion strategies.",
    difficulty: "Advanced" as const,
    estimatedTime: "30-35 שעות",
    skills: ["GitOps", "Progressive Delivery", "Canary Deployments", "Feature Flags", "ArgoCD/Flux"],
    featured: false,
  },
];