export const projects = [
  {
    id: "year-3-frontend-design-system",
    title: "Design System ו-Component Library",
    description: "בנה design system מקיף עם storybook ותיעוד",
    longDescription: "פיתוח design system מלא הכולל component library, design tokens, documentation, testing strategies, ו-CI/CD pipeline לפרסום החבילה.",
    difficulty: "Expert" as const,
    estimatedTime: "35-45 שעות",
    skills: ["Design Systems", "Storybook", "Design Tokens", "Component Architecture", "Package Publishing"],
    featured: true,
  },
  {
    id: "year-3-frontend-micro-frontends",
    title: "Micro-frontends Architecture",
    description: "בנה ארכיטקטורת micro-frontends עם module federation",
    longDescription: "יצירת ארכיטקטורת micro-frontends מורכבת עם Webpack Module Federation, shared dependencies, independent deployment וניהול state בין אפליקציות.",
    difficulty: "Expert" as const,
    estimatedTime: "40-50 שעות",
    skills: ["Micro-frontends", "Module Federation", "Webpack", "Independent Deployment", "State Management"],
    featured: true,
  },
  {
    id: "year-3-frontend-performance",
    title: "Web Performance Optimization",
    description: "אופטימיזציה מתקדמת של ביצועי web application",
    longDescription: "אופטימיזציה מקיפה של אפליקציית web כולל code splitting, lazy loading, service workers, image optimization, ו-performance monitoring.",
    difficulty: "Advanced" as const,
    estimatedTime: "25-30 שעות",
    skills: ["Performance Optimization", "Code Splitting", "Service Workers", "Web Vitals", "Performance Monitoring"],
    featured: false,
  },
  {
    id: "year-3-frontend-accessibility",
    title: "Accessibility-First Application",
    description: "בנה אפליקציה עם נגישות מלאה ו-WCAG compliance",
    longDescription: "פיתוח אפליקציה עם דגש על נגישות מקסימלית, תמיכה בקוראי מסך, keyboard navigation, ו-compliance מלא עם WCAG guidelines.",
    difficulty: "Advanced" as const,
    estimatedTime: "20-25 שעות",
    skills: ["Web Accessibility", "WCAG", "Screen Readers", "ARIA", "Inclusive Design"],
    featured: false,
  },
];